from pathlib import Path

import yaml

from src.exporters.services.molecule_project import MoleculeProject
from src.exporters.state import ExportState
from src.exporters.types import MigrationCategory
from src.types import AnsibleModule, Checklist, DocumentFile


def create_state(tmp_path: Path) -> ExportState:
    return ExportState(
        user_message="migrate module",
        path=str(tmp_path / "source"),
        module=AnsibleModule("web_server"),
        module_migration_plan=DocumentFile(
            path=Path("plan.md"), content="# Plan\n\nCheck the web service."
        ),
        high_level_migration_plan=DocumentFile(
            path=Path("high-level.md"), content="# High-level plan"
        ),
        directory_listing=[],
        current_phase="molecule_testing",
        write_attempt_counter=0,
        validation_attempt_counter=0,
        validation_report="",
        last_output="",
        checklist=Checklist("web_server", MigrationCategory),
    )


def test_project_composes_templates_writer_and_validator(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    state = create_state(tmp_path)
    project = MoleculeProject(state.layout)

    project.scaffold()

    scenario = Path("ansible/molecule/web_server")
    config = yaml.safe_load((scenario / "molecule.yml").read_text())
    assert config["driver"]["name"] == "podman"
    assert config["platforms"][0]["name"] == "x2a_web_server"
    assert config["ansible"]["executor"]["backend"] == "ansible-playbook"
    assert not (scenario / "inventory").exists()
    assert not (scenario / "create.yml").exists()
    assert not (scenario / "destroy.yml").exists()
    assert state.layout.molecule_verify_path not in project.templates.files()
    assert project.validate()  # verify.yml is generated by the LLM, not this facade


def test_project_scaffold_preserves_existing_artifacts(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    state = create_state(tmp_path)
    project = MoleculeProject(state.layout)
    project.scaffold()
    deployment = state.layout.run_playbook_path
    deployment.write_text("# user-maintained deployment entry point\n")

    project.scaffold()

    assert deployment.read_text() == "# user-maintained deployment entry point\n"
